language: python
sudo: required
dist: xenial
python: "3.7"

# set up the image with system requirements
addons:
  apt:
    update: true
    packages:
      - make
      
before_install:
  - sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
  - sudo apt-get update 
  - sudo apt-get install tesseract-ocr

branches:
  only:
    - tests
    - master 
    - develop

script:
  - tesseract -v
  - make ci
